"""
SQL Query Validator.

Validates SQL queries for safety and correctness before execution.
Implements multiple security layers to prevent SQL injection and
unauthorized operations.
"""

import re
from typing import List, Set, Optional, Tuple
from dataclasses import dataclass
import logging

from rag_framework.config.models import SQLSecurityConfig
from rag_framework.exceptions import SQLSecurityError

logger = logging.getLogger(__name__)


@dataclass
class ValidationResult:
    """Result of SQL query validation."""

    is_valid: bool
    query: str  # Possibly sanitized query
    errors: List[str]
    warnings: List[str]

    def __bool__(self) -> bool:
        """Allow boolean evaluation of validation result."""
        return self.is_valid


class QueryValidator:
    """
    Validates SQL queries for safety before execution.

    This validator implements multiple security layers:
    1. Statement type checking (only SELECT allowed by default)
    2. Forbidden pattern detection (injection patterns)
    3. Table/column whitelist validation
    4. Query complexity limits

    Security is critical since SQL is generated by an LLM which
    could potentially be manipulated by adversarial prompts.
    """

    # SQL statement patterns
    STATEMENT_PATTERNS = {
        "SELECT": r"^\s*SELECT\b",
        "INSERT": r"^\s*INSERT\b",
        "UPDATE": r"^\s*UPDATE\b",
        "DELETE": r"^\s*DELETE\b",
        "DROP": r"^\s*DROP\b",
        "ALTER": r"^\s*ALTER\b",
        "CREATE": r"^\s*CREATE\b",
        "TRUNCATE": r"^\s*TRUNCATE\b",
        "GRANT": r"^\s*GRANT\b",
        "REVOKE": r"^\s*REVOKE\b",
    }

    # Patterns that indicate potential SQL injection
    INJECTION_PATTERNS = [
        r";\s*--",  # Comment after statement
        r";\s*/\*",  # Block comment after statement
        r"'\s*OR\s*'1'\s*=\s*'1",  # Classic OR injection
        r"'\s*OR\s+1\s*=\s*1",  # Numeric OR injection
        r"INTO\s+OUTFILE",  # File write attempt
        r"INTO\s+DUMPFILE",  # File write attempt
        r"LOAD_FILE\s*\(",  # File read attempt
        r"BENCHMARK\s*\(",  # Time-based attack
        r"SLEEP\s*\(",  # Time-based attack
        r"WAITFOR\s+DELAY",  # SQL Server delay
        r";\s*(?:DROP|DELETE|UPDATE|INSERT|ALTER|CREATE)",  # Chained dangerous statements
    ]

    def __init__(
        self,
        config: SQLSecurityConfig,
        allowed_tables: Optional[Set[str]] = None,
        allowed_columns: Optional[Set[str]] = None,
    ):
        """
        Initialize query validator.

        Args:
            config: Security configuration
            allowed_tables: Set of allowed table names (whitelist)
            allowed_columns: Set of allowed column names (whitelist)
        """
        self.config = config
        self.allowed_tables = allowed_tables or set()
        self.allowed_columns = allowed_columns or set()

        # Compile forbidden patterns from config
        self._forbidden_patterns = [
            re.compile(p, re.IGNORECASE) for p in config.forbidden_patterns
        ]

        # Compile injection patterns
        self._injection_patterns = [
            re.compile(p, re.IGNORECASE) for p in self.INJECTION_PATTERNS
        ]

    def validate(self, query: str) -> ValidationResult:
        """
        Validate a SQL query for safety and correctness.

        Args:
            query: The SQL query to validate

        Returns:
            ValidationResult with validation status and any issues
        """
        errors: List[str] = []
        warnings: List[str] = []

        # Normalize query
        query = self._normalize_query(query)

        # Check for empty query
        if not query or not query.strip():
            return ValidationResult(
                is_valid=False,
                query=query,
                errors=["Empty query"],
                warnings=[],
            )

        # Check statement type
        if self.config.allow_only_select:
            if not self._is_select_only(query):
                errors.append("Only SELECT statements are allowed")

        # Check for injection patterns
        injection_issues = self._check_injection_patterns(query)
        errors.extend(injection_issues)

        # Check for forbidden patterns
        forbidden_issues = self._check_forbidden_patterns(query)
        errors.extend(forbidden_issues)

        # Check query complexity
        complexity_warnings = self._check_complexity(query)
        warnings.extend(complexity_warnings)

        # Check table whitelist (if configured)
        if self.allowed_tables:
            table_issues = self._check_tables(query)
            errors.extend(table_issues)

        logger.debug(
            f"Query validation: valid={len(errors) == 0}, "
            f"errors={len(errors)}, warnings={len(warnings)}"
        )

        return ValidationResult(
            is_valid=len(errors) == 0,
            query=query,
            errors=errors,
            warnings=warnings,
        )

    def _normalize_query(self, query: str) -> str:
        """Normalize query by removing extra whitespace."""
        # Remove leading/trailing whitespace
        query = query.strip()

        # Remove multiple spaces
        query = re.sub(r"\s+", " ", query)

        # Remove trailing semicolons (we'll add one if needed)
        query = query.rstrip(";")

        return query

    def _is_select_only(self, query: str) -> bool:
        """Check if query is a SELECT statement only."""
        # Check that it starts with SELECT
        if not re.match(self.STATEMENT_PATTERNS["SELECT"], query, re.IGNORECASE):
            return False

        # Check for any other statement types (could be in subqueries or chained)
        for stmt_type, pattern in self.STATEMENT_PATTERNS.items():
            if stmt_type == "SELECT":
                continue
            # Check if dangerous statement appears outside of quoted strings
            if self._pattern_outside_quotes(pattern, query):
                return False

        return True

    def _pattern_outside_quotes(self, pattern: str, query: str) -> bool:
        """
        Check if pattern matches outside of quoted strings.

        This is important for detecting injected statements that
        aren't part of string literals.
        """
        # Simple approach: remove quoted strings, then check
        # Remove single-quoted strings
        sanitized = re.sub(r"'[^']*'", "", query)
        # Remove double-quoted strings
        sanitized = re.sub(r'"[^"]*"', "", sanitized)

        return bool(re.search(pattern, sanitized, re.IGNORECASE))

    def _check_injection_patterns(self, query: str) -> List[str]:
        """Check for SQL injection patterns."""
        issues = []

        for pattern in self._injection_patterns:
            if pattern.search(query):
                issues.append(
                    f"Potential SQL injection detected: pattern '{pattern.pattern}'"
                )
                logger.warning(
                    f"SQL injection pattern detected in query: {query[:100]}"
                )

        return issues

    def _check_forbidden_patterns(self, query: str) -> List[str]:
        """Check for forbidden patterns from configuration."""
        issues = []

        for pattern in self._forbidden_patterns:
            if pattern.search(query):
                issues.append(f"Forbidden pattern detected: '{pattern.pattern}'")

        return issues

    def _check_complexity(self, query: str) -> List[str]:
        """Check query complexity and return warnings."""
        warnings = []

        # Count JOINs
        join_count = len(re.findall(r"\bJOIN\b", query, re.IGNORECASE))
        if join_count > 3:
            warnings.append(f"Complex query with {join_count} JOINs")

        # Count subqueries
        subquery_count = query.upper().count("SELECT") - 1
        if subquery_count > 2:
            warnings.append(f"Query has {subquery_count} subqueries")

        # Check for wildcards
        if "SELECT *" in query.upper():
            warnings.append("SELECT * may return excessive data")

        return warnings

    def _check_tables(self, query: str) -> List[str]:
        """Check that only whitelisted tables are accessed."""
        issues = []

        # Extract table names from query (simplified extraction)
        # This catches: FROM table, JOIN table, INTO table
        table_pattern = r"(?:FROM|JOIN|INTO)\s+([a-zA-Z_][a-zA-Z0-9_]*)"
        matches = re.findall(table_pattern, query, re.IGNORECASE)

        for table in matches:
            if table.upper() not in {t.upper() for t in self.allowed_tables}:
                issues.append(f"Table '{table}' is not in allowed list")

        return issues

    def _add_limit(self, query: str) -> str:
        """Add LIMIT clause to query if not present."""
        # Don't add LIMIT if query already has it or has aggregation
        query_upper = query.upper()

        if "LIMIT" in query_upper:
            return query

        # Check for aggregation (COUNT, SUM, etc.) which typically returns few rows
        aggregations = ["COUNT(", "SUM(", "AVG(", "MIN(", "MAX("]
        if any(agg in query_upper for agg in aggregations):
            if "GROUP BY" not in query_upper:
                return query  # Single aggregation result

        return f"{query} LIMIT {self.config.max_rows}"

    def quick_check(self, query: str) -> bool:
        """
        Quick boolean check if query is likely safe.

        This is a fast check for use in tight loops. For detailed
        validation, use validate() instead.
        """
        try:
            result = self.validate(query)
            return result.is_valid
        except Exception:
            return False

    def sanitize(self, query: str) -> Tuple[str, List[str]]:
        """
        Attempt to sanitize a query and return warnings.

        This method tries to make a query safe by removing
        potentially dangerous elements. Use with caution.

        Returns:
            Tuple of (sanitized_query, list_of_changes)
        """
        changes = []

        # Remove trailing semicolons
        if query.rstrip().endswith(";"):
            query = query.rstrip(";").rstrip()
            changes.append("Removed trailing semicolon")

        # Remove comments
        if "--" in query:
            query = re.sub(r"--.*$", "", query, flags=re.MULTILINE)
            changes.append("Removed line comments")

        if "/*" in query:
            query = re.sub(r"/\*.*?\*/", "", query, flags=re.DOTALL)
            changes.append("Removed block comments")

        return query.strip(), changes
